
# 应用端口
server:
  port: 6351
spring:
  application:
    # 应用名称
    name: cloud-provider-user

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://jorian:123456@localhost:7315/eureka

logging:
  level:
    root: INFO
