spring:
  security:
    basic:
      enabled: true
    user:
      name: jorian
      password: 123456
server:
  port: 7315

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://jorian:123456@localhost:7315/eureka
